services:
  evenezer-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evenezer-web
    command: evenezer
    ports:
      - "8090:8090"
    environment:
      - EVENEZER_HOST=0.0.0.0
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    restart: unless-stopped

  evenezer-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evenezer-bot
    command: evenezer-bot
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    restart: unless-stopped
